### ISSUE TITLE
Menüde resim yoksa default resim atılması lazım

### ISSUE THREAD

**Issue by emreilhangithub** [Fupico/QRMenu-UI#10]
![menuresmiyok](https://github.com/user-attachments/assets/466b7815-2e0c-47d1-ac77-e33b8a399d75)

Menüde resim yoksa default resim eklenmesi lazım !!!

**Comment by devrimmehmet** [comment]
Menü Grupları için bu dizayn yapıldı. Varsayılan resim atandı. Commit: f8d35cf476de8a6c6dd2d2be5fa0c11ee16c4aaa

**Comment by devrimmehmet** [comment]
Tamamlandı. Commit:8f0ae064e2fdc743187f24cabf62aaf3d1678a62
