### ISSUE TITLE
Yemek bulamadığı için yemekleri listelemiyor !!

### ISSUE THREAD

**Issue by emreilhangithub** [Fupico/QRMenu-UI#8]
![Ekran görüntüsü 2024-10-26 210505](https://github.com/user-attachments/assets/ffa330ec-4fb9-44d3-a7bd-e811e7ac5974)

Yeni menü grubu ekledim. Fakat Yemekler yeşil renkli olan butona basınca ekran görüntüsündeki hatayı veriyor.
Yani özetle yemek bulamadığı için yemekleri listelemiyor !!

**Comment by devrimmehmet** [comment]
Tamamlandı.
