### ISSUE TITLE
Yemek fiyatını güncelleyince anlık fiyatı güncellemiyor.

### ISSUE THREAD

**Issue by emreilhangithub** [Fupico/QRMenu-UI#9]
![yemekfiyatguncelleme](https://github.com/user-attachments/assets/e1b8e5de-84a3-44c6-8adc-56de5aa26ef9)

Yemek fiyatını güncelledim ama sayfada anlık fiyat güncellemesi olmadı eski fiyat gözüküyor.
Ekran görüntüsündeki hatayı verdi. Sayfayı refresh edince yeni fiyatı yapıyor.

**Comment by devrimmehmet** [comment]
Tamamlandı. Commit:8f0ae064e2fdc743187f24cabf62aaf3d1678a62
